# Generated by Django 5.2.6 on 2025-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Business', 'Business'), ('Technology', 'Technology'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education')], default='Business', max_length=50),
        ),
    ]
